title: "Софт"
icon: "diskette.png"
order: 5
children:
  - title: "Игры"
    icon: "games_control.png"
    children:
      - title: "Все"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/all"
      - title: "Аркады"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/arcade"
      - title: "Гонки"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/car"
      - title: "Спортивные"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/sport"
      - title: "Логические"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/logic"
      - title: "Обучающие"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/edu"
      - title: "Прочие"
        searchId: "soft-search"
        endpoint: "/api/v1/soft/games/other"
  - title: "Утилиты"
    searchId: "soft-search"
    endpoint: "/api/v1/soft/tools"
  - title: "Системные"
    searchId: "soft-search"
    endpoint: "/api/v1/soft/system"
  - title: "Программирование"
    searchId: "soft-search"
    endpoint: "/api/v1/soft/code"
  - title: "Остальные"
    searchId: "soft-search"
    endpoint: "/api/v1/soft/other"

  - title: "Поиск"
    type: "input"
    menuId: "soft-search"
    placeholder: "Введите запрос..."
    icon: "search.png"
