- title: "Главная"
  icon: "home.png"
  url: "/api/v1/index"

- title: "О компьютере"
  icon: "pk8000.png"
  children:
    - title: "Описание"
      url: "/api/v1/about/history"
    - title: "Галерея"
      icon: "camera.png"
      children:
        - title: "Сура"
          url: "/api/v1/about/sura"
        - title: "Веста"
          url: "/api/v1/about/vesta"
        - title: "Хобби"
          url: "/api/v1/about/hobby"
    - title: "Статьи"
      url: "/api/v1/about/articles"

- title: "Документация"
  icon: "document.png"
  children:
    - title: "Сура"
      url: "/api/v1/docs/sura"
    - title: "Веста"
      url: "/api/v1/docs/vesta"
    - title: "Хобби"
      url: "/api/v1/docs/hobby"
    - title: "Схемы"
      url: "/api/v1/docs/schemes"
    - title: "Разное"
      icon: "documents.png"
      children:
        - title: "CP/M"
          url: "/api/v1/docs/cp-m"
        - title: "PL/M"
          url: "/api/v1/docs/pl-m"

- title: "Контроллеры"
  icon: "gear.png"
  children:
    - title: "TV-адаптеры"
      icon: "monitor.png"
      children:
        - title: "ТВ-адаптер"
          url: "/api/v1/hardware/tv-adapter"
        - title: "PAL-TV"
          url: "/api/v1/hardware/pal-tv"
        - title: "EGA"
          url: "/api/v1/hardware/ega"
    - title: "AY-адаптеры"
      icon: "speaker.png"
      children:
        - title: "AY версии 1.1"
          url: "/api/v1/hardware/AY-LUT"
        - title: "AY версии 1.2"
          url: "/api/v1/hardware/AY-ver12"
    - title: "HDD"
      url: "/api/v1/hardware/hdd"
    - title: "FDD"
      url: "/api/v1/hardware/fdd"
    - title: "RTC"
      url: "/api/v1/hardware/rtc"

- title: "Софт"
  icon: "diskette.png"
  children:
    - title: "Игры"
      icon: "games_control.png"
      children:
        - title: "Все"
          searchId: "soft-search"
          url: "/api/v1/soft/games/all"
        - title: "Аркады"
          searchId: "soft-search"
          url: "/api/v1/soft/games/arcade"
        - title: "Гонки"
          searchId: "soft-search"
          url: "/api/v1/soft/games/car"
        - title: "Спортивные"
          searchId: "soft-search"
          url: "/api/v1/soft/games/sport"
        - title: "Логические"
          searchId: "soft-search"
          url: "/api/v1/soft/games/logic"
        - title: "Обучающие"
          searchId: "soft-search"
          url: "/api/v1/soft/games/edu"
        - title: "Остальные"
          searchId: "soft-search"
          url: "/api/v1/soft/games/other"
    - title: "Системные"
      searchId: "soft-search"
      url: "/api/v1/soft/system"

    - title: "Поиск"
      type: "input"
      id: "soft-search"
      placeholder: "Введите запрос..."
      icon: "search.png"

- title: "Обратная связь"
  icon: "phone.png"
  url: "/api/v1/contacts"
