USE catalog_db;

INSERT INTO products (name, short_description, description_cache, category_id) VALUES
    ('Клад', 'Сбор кладов в лабиринте.', '-', ${CATEGORY_ARCADE}),
    ('Пилот', 'Бомбардировка города.', '-', ${CATEGORY_ARCADE}),
    ('Питон (Фотон)', 'Питон охотится на кроликов.', '-', ${CATEGORY_ARCADE}),
    ('Угадай число', 'Игра на логику.', '-', ${CATEGORY_LOGIC}),
    ('Тяп-ляп', 'Тетрис.', '-', ${CATEGORY_ARCADE}),
    ('Тест', 'Тест компьютера.', '-', ${CATEGORY_TOOLS}),
    ('Минер', 'Прохождение по минному полю.', '-', ${CATEGORY_LOGIC}),
    ('Морской бой', 'Упрощенная версия настольной игры.', '-', ${CATEGORY_LOGIC}),
    ('Автодром', 'Поездка на автомобиле по небольшой трассе.', '-', ${CATEGORY_RACING}),
    ('Сура', 'Клавиатурный тренажер.', '-', ${CATEGORY_EDU}),
    ('Танец', 'Танцующий человечек.', '-', ${CATEGORY_OTHER_GAMES}),
    ('Шахматы', 'Шахматы. Вполне неплохой AI.', '-', ${CATEGORY_LOGIC}),
    ('Пожарник', 'Спасение мышек из горящего здания.', '-', ${CATEGORY_ARCADE}),
    ('Тест-Хобби', 'Тест компьютера. Версия от ПК "Хобби"', '-', ${CATEGORY_TOOLS}),
    ('Алибаба', 'Пусть и не сорок, но разбойники присутствуют.', '-', ${CATEGORY_ARCADE}),
    ('Binary land', '-', '-', ${CATEGORY_ARCADE}),
    ('Crux', 'Нечто среднее между тетрисом и цветными линиями.', '-', ${CATEGORY_LOGIC}),
    ('Кобра', 'Полет на боевом вертолете.', '-', ${CATEGORY_ARCADE}),
    ('Boulder dash', 'Классический Boulder.', '-', ${CATEGORY_ARCADE}),
    ('Bomber man', 'Уничтожение врагов минами.', '-', ${CATEGORY_ARCADE}),
    ('File manager', 'Файловый менеджер под CM/M', '-', ${CATEGORY_TOOLS}),
    ('Image view', 'Вьюнер всех известных форматов изображений для 8-битных компьютеров.', '-', ${CATEGORY_OTHER_SOFTWARE}),
    ('STC Player', 'Плеер STC-музыки для AY-контроллера.', '-', ${CATEGORY_OTHER_SOFTWARE}),
    ('Питон', 'Классический питон.', '-', ${CATEGORY_ARCADE}),
    ('Двигалка', 'Логическая игра на смекалку.', '-', ${CATEGORY_LOGIC}),
    ('Bolder dash', 'Порт аналогичной DOS-игры, являющейся портом с Электроника БК-0010.', '-', ${CATEGORY_ARCADE}),
    ('High way', 'Езда по городу. Что-то собираем и избегаем встреч с врагами.', '-', ${CATEGORY_RACING});
