version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-site-pk8000
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env.mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.8
    container_name: keycloak-site-pk8000
    env_file:
      - .env.keycloak
    ports:
      - "8080:8080/tcp"
    command: start-dev --http-port=8080 --features=scripts
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - keycloak-network
    profiles: ["manual"]

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak-and-mysql-volume:
